volumes:
  xt_sysrq_docker:
    external: true
    
services:
  xt_sysrq_docker:
    # Uncomment one of these. Use :latest if you want the stable build, use :dev if you want the development build
    image: iainbullock/xt_sysrq_docker:latest
    #image: iainbullock/xt_sysrq_docker:dev
    container_name: xt_sysrq_docker
   
    volumes:
      - xt_sysrq_docker:/config
    
    network_mode: host
    
    cap_add:
      - NET_ADMIN

    environment:
      - AP_IFACE=wlan0
      - UPLINK_IFACE=eth0
      
    # Allow opening of a shell in container
    tty: true
    stdin_open: true    
    # Uncomment if you need a container shell when the container won't run 
    # entrypoint: "/bin/ash"
    
    restart: unless-stopped
